# Generated by Django 3.1.4 on 2020-12-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20201211_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=''),
        ),
    ]
