# Generated by Django 3.1.4 on 2020-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20201211_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=False),
        ),
    ]
